In [1]:
import pandas as pd

# Replace 'your_file.csv' with your actual file path or name
df = pd.read_csv('probe.csv')

# To check the data
df['frame.time_delta']=df['frame.time_delta'].apply(lambda x: format(x, '.6f'))
df['ip.len'] = pd.to_numeric(df['ip.len'], errors='coerce').astype('Int64')
df['ip.flags.df'] = pd.to_numeric(df['ip.flags.df'], errors='coerce').astype('Int64')
df['ip.flags.mf'] = pd.to_numeric(df['ip.flags.mf'], errors='coerce').astype('Int64')
df['ip.ttl'] = pd.to_numeric(df['ip.ttl'], errors='coerce').astype('Int64')
df['ip.proto'] = pd.to_numeric(df['ip.proto'], errors='coerce').astype('Int64')
df['frame.time_delta'] = pd.to_numeric(df['frame.time_delta'], errors='coerce').astype('float64')
df['ip.src'] = df['ip.src'].str.replace('.', '', regex=False)
df['ip.dst'] = df['ip.dst'].str.replace('.', '', regex=False)
df['ip.src'] = pd.to_numeric(df['ip.src'], errors='coerce').astype('Int64')
df['ip.dst'] = pd.to_numeric(df['ip.dst'], errors='coerce').astype('Int64')
df=df.dropna()
print(df.head())

         ip.src        ip.dst  ip.len  ip.flags.df  ip.flags.mf  ip.fragment  \
0  192168202128    1921682022      74            1            0            0
1    1921682022  192168202128      74            0            0            0
2  192168202128  192168202129      44            0            0            0
3  192168202128  192168202129      44            0            0            0
4  192168202128  192168202129      44            0            0            0

   ip.fragment.count  ip.fragments  ip.ttl  ip.proto  ...  tcp.flags  \
0                  0             0      64        17  ...        0.0
1                  0             0     128        17  ...        0.0
2                  0             0      48         6  ...        2.0
3                  0             0      53         6  ...        2.0
4                  0             0      48         6  ...        2.0

   tcp.analysis.ack_rtt  tcp.segments  tcp.reassembled.length  http.request  \
0                   0.0             0                       0             0
1                   0.0             0                       0             0
2                   0.0             0                       0             0
3                   0.0             0                       0             0
4                   0.0             0                       0             0

   udp.port  frame.time_relative  frame.time_delta  tcp.time_relative  \
0   5225453             0.071174          0.071155                0.0
1   5352254             0.113938          0.042764                0.0
2         0             0.139608          0.025670                0.0
3         0             0.139608          0.000000                0.0
4         0             0.139608          0.000000                0.0

   tcp.time_delta
0             0.0
1             0.0
2             0.0
3             0.0
4             0.0

[5 rows x 26 columns]

In [2]:
df["label"]="probe"
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30048 entries, 0 to 31667
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  30048 non-null  Int64
 1   ip.dst                  30048 non-null  Int64
 2   ip.len                  30048 non-null  Int64
 3   ip.flags.df             30048 non-null  Int64
 4   ip.flags.mf             30048 non-null  Int64
 5   ip.fragment             30048 non-null  int64
 6   ip.fragment.count       30048 non-null  int64
 7   ip.fragments            30048 non-null  int64
 8   ip.ttl                  30048 non-null  Int64
 9   ip.proto                30048 non-null  Int64
 10  tcp.window_size         30048 non-null  float64
 11  tcp.ack                 30048 non-null  float64
 12  tcp.seq                 30048 non-null  float64
 13  tcp.len                 30048 non-null  float64
 14  tcp.stream              30048 non-null  float64
 15  tcp.urgent_pointer      30048 non-null  float64
 16  tcp.flags               30048 non-null  float64
 17  tcp.analysis.ack_rtt    30048 non-null  float64
 18  tcp.segments            30048 non-null  int64
 19  tcp.reassembled.length  30048 non-null  int64
 20  http.request            30048 non-null  int64
 21  udp.port                30048 non-null  int64
 22  frame.time_relative     30048 non-null  float64
 23  frame.time_delta        30048 non-null  float64
 24  tcp.time_relative       30048 non-null  float64
 25  tcp.time_delta          30048 non-null  float64
 26  label                   30048 non-null  object
dtypes: Int64(7), float64(12), int64(7), object(1)
memory usage: 6.6+ MB

In [3]:
df_bf=pd.read_csv("bruteforce.csv")
df_bf.head()

,ip.src,ip.dst,ip.len,ip.flags.df,ip.flags.mf,ip.fragment,ip.fragment.count,ip.fragments,ip.ttl,ip.proto,...,tcp.flags,tcp.analysis.ack_rtt,tcp.segments,tcp.reassembled.length,http.request,udp.port,frame.time_relative,frame.time_delta,tcp.time_relative,tcp.time_delta
0,192.168.202.128,192.168.202.129,60,1,0,0,0,0,64,6,...,2,0.000000,0,0,0,0,0.000000,0.000000,0.000000,0.000000
1,192.168.202.129,192.168.202.128,60,1,0,0,0,0,64,6,...,12,0.000386,0,0,0,0,0.000386,0.000386,0.000386,0.000386
2,192.168.202.128,192.168.202.129,52,1,0,0,0,0,64,6,...,10,0.000668,0,0,0,0,0.001054,0.000668,0.001054,0.000668
3,192.168.202.128,192.168.202.129,60,1,0,0,0,0,64,6,...,2,0.000000,0,0,0,0,0.001351,0.000297,0.000000,0.000000
4,192.168.202.129,192.168.202.128,60,1,0,0,0,0,64,6,...,12,0.000013,0,0,0,0,0.001364,0.000013,0.000013,0.000013

In [4]:
df_bf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26585 entries, 0 to 26584
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  26585 non-null  object
 1   ip.dst                  26585 non-null  object
 2   ip.len                  26585 non-null  int64
 3   ip.flags.df             26585 non-null  object
 4   ip.flags.mf             26585 non-null  int64
 5   ip.fragment             26585 non-null  int64
 6   ip.fragment.count       26585 non-null  int64
 7   ip.fragments            26585 non-null  int64
 8   ip.ttl                  26585 non-null  int64
 9   ip.proto                26585 non-null  int64
 10  tcp.window_size         26585 non-null  int64
 11  tcp.ack                 26585 non-null  int64
 12  tcp.seq                 26585 non-null  int64
 13  tcp.len                 26585 non-null  int64
 14  tcp.stream              26585 non-null  int64
 15  tcp.urgent_pointer      26585 non-null  int64
 16  tcp.flags               26585 non-null  int64
 17  tcp.analysis.ack_rtt    26585 non-null  float64
 18  tcp.segments            26585 non-null  int64
 19  tcp.reassembled.length  26585 non-null  int64
 20  http.request            26585 non-null  int64
 21  udp.port                26585 non-null  int64
 22  frame.time_relative     26585 non-null  float64
 23  frame.time_delta        26585 non-null  float64
 24  tcp.time_relative       26585 non-null  float64
 25  tcp.time_delta          26585 non-null  float64
dtypes: float64(5), int64(18), object(3)
memory usage: 5.3+ MB

In [5]:
l=[]
for i in df_bf['ip.len']:
    if i not in l:
        l.append(i)
print(l)
print(len(df_bf['ip.len']))

[60, 52, 136, 227, 1500, 477, 1925, 236, 558, 234, 239, 238, 244, 237, 235, 2006, 233, 240, 243, 232, 64, 68, 40, 247, 242, 241, 246, 245, 0, 248]
26585

In [6]:
df_bf['ip.len'] = pd.to_numeric(df_bf['ip.len'], errors='coerce').astype('Int64')
df_bf['ip.flags.df'] = pd.to_numeric(df_bf['ip.flags.df'], errors='coerce').astype('Int64')
df_bf['ip.flags.mf'] = pd.to_numeric(df_bf['ip.flags.mf'], errors='coerce').astype('Int64')
df_bf['ip.ttl'] = pd.to_numeric(df_bf['ip.ttl'], errors='coerce').astype('Int64')
df_bf['ip.proto'] = pd.to_numeric(df_bf['ip.proto'], errors='coerce').astype('Int64')
df_bf['frame.time_delta'] = pd.to_numeric(df_bf['frame.time_delta'], errors='coerce').astype('float64')
df_bf['ip.src'] = df_bf['ip.src'].str.replace('.', '', regex=False)
df_bf['ip.dst'] = df_bf['ip.dst'].str.replace('.', '', regex=False)
df_bf['ip.src'] = pd.to_numeric(df_bf['ip.src'], errors='coerce').astype('Int64')
df_bf['ip.dst'] = pd.to_numeric(df_bf['ip.dst'], errors='coerce').astype('Int64')

In [7]:
df_bf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26585 entries, 0 to 26584
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  26585 non-null  Int64
 1   ip.dst                  26585 non-null  Int64
 2   ip.len                  26585 non-null  Int64
 3   ip.flags.df             26583 non-null  Int64
 4   ip.flags.mf             26585 non-null  Int64
 5   ip.fragment             26585 non-null  int64
 6   ip.fragment.count       26585 non-null  int64
 7   ip.fragments            26585 non-null  int64
 8   ip.ttl                  26585 non-null  Int64
 9   ip.proto                26585 non-null  Int64
 10  tcp.window_size         26585 non-null  int64
 11  tcp.ack                 26585 non-null  int64
 12  tcp.seq                 26585 non-null  int64
 13  tcp.len                 26585 non-null  int64
 14  tcp.stream              26585 non-null  int64
 15  tcp.urgent_pointer      26585 non-null  int64
 16  tcp.flags               26585 non-null  int64
 17  tcp.analysis.ack_rtt    26585 non-null  float64
 18  tcp.segments            26585 non-null  int64
 19  tcp.reassembled.length  26585 non-null  int64
 20  http.request            26585 non-null  int64
 21  udp.port                26585 non-null  int64
 22  frame.time_relative     26585 non-null  float64
 23  frame.time_delta        26585 non-null  float64
 24  tcp.time_relative       26585 non-null  float64
 25  tcp.time_delta          26585 non-null  float64
dtypes: Int64(7), float64(5), int64(14)
memory usage: 5.5 MB

In [8]:
df_bf.head()

,ip.src,ip.dst,ip.len,ip.flags.df,ip.flags.mf,ip.fragment,ip.fragment.count,ip.fragments,ip.ttl,ip.proto,...,tcp.flags,tcp.analysis.ack_rtt,tcp.segments,tcp.reassembled.length,http.request,udp.port,frame.time_relative,frame.time_delta,tcp.time_relative,tcp.time_delta
0,192168202128,192168202129,60,1,0,0,0,0,64,6,...,2,0.000000,0,0,0,0,0.000000,0.000000,0.000000,0.000000
1,192168202129,192168202128,60,1,0,0,0,0,64,6,...,12,0.000386,0,0,0,0,0.000386,0.000386,0.000386,0.000386
2,192168202128,192168202129,52,1,0,0,0,0,64,6,...,10,0.000668,0,0,0,0,0.001054,0.000668,0.001054,0.000668
3,192168202128,192168202129,60,1,0,0,0,0,64,6,...,2,0.000000,0,0,0,0,0.001351,0.000297,0.000000,0.000000
4,192168202129,192168202128,60,1,0,0,0,0,64,6,...,12,0.000013,0,0,0,0,0.001364,0.000013,0.000013,0.000013

In [9]:
df_bf['label']='bruteforce'

In [10]:
df_bf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26585 entries, 0 to 26584
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  26585 non-null  Int64
 1   ip.dst                  26585 non-null  Int64
 2   ip.len                  26585 non-null  Int64
 3   ip.flags.df             26583 non-null  Int64
 4   ip.flags.mf             26585 non-null  Int64
 5   ip.fragment             26585 non-null  int64
 6   ip.fragment.count       26585 non-null  int64
 7   ip.fragments            26585 non-null  int64
 8   ip.ttl                  26585 non-null  Int64
 9   ip.proto                26585 non-null  Int64
 10  tcp.window_size         26585 non-null  int64
 11  tcp.ack                 26585 non-null  int64
 12  tcp.seq                 26585 non-null  int64
 13  tcp.len                 26585 non-null  int64
 14  tcp.stream              26585 non-null  int64
 15  tcp.urgent_pointer      26585 non-null  int64
 16  tcp.flags               26585 non-null  int64
 17  tcp.analysis.ack_rtt    26585 non-null  float64
 18  tcp.segments            26585 non-null  int64
 19  tcp.reassembled.length  26585 non-null  int64
 20  http.request            26585 non-null  int64
 21  udp.port                26585 non-null  int64
 22  frame.time_relative     26585 non-null  float64
 23  frame.time_delta        26585 non-null  float64
 24  tcp.time_relative       26585 non-null  float64
 25  tcp.time_delta          26585 non-null  float64
 26  label                   26585 non-null  object
dtypes: Int64(7), float64(5), int64(14), object(1)
memory usage: 5.7+ MB

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30048 entries, 0 to 31667
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  30048 non-null  Int64
 1   ip.dst                  30048 non-null  Int64
 2   ip.len                  30048 non-null  Int64
 3   ip.flags.df             30048 non-null  Int64
 4   ip.flags.mf             30048 non-null  Int64
 5   ip.fragment             30048 non-null  int64
 6   ip.fragment.count       30048 non-null  int64
 7   ip.fragments            30048 non-null  int64
 8   ip.ttl                  30048 non-null  Int64
 9   ip.proto                30048 non-null  Int64
 10  tcp.window_size         30048 non-null  float64
 11  tcp.ack                 30048 non-null  float64
 12  tcp.seq                 30048 non-null  float64
 13  tcp.len                 30048 non-null  float64
 14  tcp.stream              30048 non-null  float64
 15  tcp.urgent_pointer      30048 non-null  float64
 16  tcp.flags               30048 non-null  float64
 17  tcp.analysis.ack_rtt    30048 non-null  float64
 18  tcp.segments            30048 non-null  int64
 19  tcp.reassembled.length  30048 non-null  int64
 20  http.request            30048 non-null  int64
 21  udp.port                30048 non-null  int64
 22  frame.time_relative     30048 non-null  float64
 23  frame.time_delta        30048 non-null  float64
 24  tcp.time_relative       30048 non-null  float64
 25  tcp.time_delta          30048 non-null  float64
 26  label                   30048 non-null  object
dtypes: Int64(7), float64(12), int64(7), object(1)
memory usage: 6.6+ MB

In [12]:
half_df = pd.concat([df, df_bf], ignore_index=True)

In [13]:
half_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56633 entries, 0 to 56632
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  56633 non-null  Int64
 1   ip.dst                  56633 non-null  Int64
 2   ip.len                  56633 non-null  Int64
 3   ip.flags.df             56631 non-null  Int64
 4   ip.flags.mf             56633 non-null  Int64
 5   ip.fragment             56633 non-null  int64
 6   ip.fragment.count       56633 non-null  int64
 7   ip.fragments            56633 non-null  int64
 8   ip.ttl                  56633 non-null  Int64
 9   ip.proto                56633 non-null  Int64
 10  tcp.window_size         56633 non-null  float64
 11  tcp.ack                 56633 non-null  float64
 12  tcp.seq                 56633 non-null  float64
 13  tcp.len                 56633 non-null  float64
 14  tcp.stream              56633 non-null  float64
 15  tcp.urgent_pointer      56633 non-null  float64
 16  tcp.flags               56633 non-null  float64
 17  tcp.analysis.ack_rtt    56633 non-null  float64
 18  tcp.segments            56633 non-null  int64
 19  tcp.reassembled.length  56633 non-null  int64
 20  http.request            56633 non-null  int64
 21  udp.port                56633 non-null  int64
 22  frame.time_relative     56633 non-null  float64
 23  frame.time_delta        56633 non-null  float64
 24  tcp.time_relative       56633 non-null  float64
 25  tcp.time_delta          56633 non-null  float64
 26  label                   56633 non-null  object
dtypes: Int64(7), float64(12), int64(7), object(1)
memory usage: 12.0+ MB

In [14]:
half_df = half_df.sample(frac=1).reset_index(drop=True)

half_df.head(100)

,ip.src,ip.dst,ip.len,ip.flags.df,ip.flags.mf,ip.fragment,ip.fragment.count,ip.fragments,ip.ttl,ip.proto,...,tcp.analysis.ack_rtt,tcp.segments,tcp.reassembled.length,http.request,udp.port,frame.time_relative,frame.time_delta,tcp.time_relative,tcp.time_delta,label
0,192168202128,192168202129,44,0,0,0,0,0,56,6,...,0.000000e+00,0,0,0,0,10.091844,0.000000,0.000000e+00,0.000000e+00,probe
1,1921682022,192168202128,40,0,0,0,0,0,128,6,...,1.220000e-07,0,0,0,0,34.831474,0.000000,1.220000e-07,1.220000e-07,probe
2,192168202129,192168202128,52,1,0,0,0,0,64,6,...,0.000000e+00,0,0,0,0,10.187213,0.000235,1.267354e-02,1.003878e-02,bruteforce
3,192168202128,192168202129,136,1,0,0,0,0,64,6,...,0.000000e+00,0,0,1,0,3.217006,0.000069,4.975220e-04,6.901100e-05,bruteforce
4,192168202128,192168202129,52,1,0,0,0,0,64,6,...,6.119660e-04,0,0,0,0,3.421080,0.000470,7.553475e-03,4.699980e-04,bruteforce
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,192168202128,192168202254,44,0,0,0,0,0,53,6,...,0.000000e+00,0,0,0,0,89.247152,0.000117,0.000000e+00,0.000000e+00,probe
96,192168202129,192168202128,40,1,0,0,0,0,64,6,...,7.394000e-06,0,0,0,0,99.730437,0.000007,7.394000e-06,7.394000e-06,probe
97,192168202129,192168202128,558,1,0,0,0,0,64,6,...,0.000000e+00,1,2129,0,0,15.474503,0.000017,5.163238e-03,1.723500e-05,bruteforce
98,192168202129,192168202128,40,1,0,0,0,0,64,6,...,2.350700e-05,0,0,0,0,99.771803,0.000016,2.350700e-05,2.350700e-05,probe
99,192168202129,192168202128,60,1,0,0,0,0,64,6,...,5.712000e-06,0,0,0,0,14.377580,0.000006,5.712000e-06,5.712000e-06,bruteforce

In [15]:
df_dos=pd.read_csv("ddosnew1.csv")

In [16]:
df_dos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30024 entries, 0 to 30023
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  30024 non-null  object
 1   ip.dst                  30024 non-null  object
 2   ip.len                  30024 non-null  int64
 3   ip.flags.df             30024 non-null  int64
 4   ip.flags.mf             30024 non-null  int64
 5   ip.fragment             30024 non-null  int64
 6   ip.fragment.count       30024 non-null  int64
 7   ip.fragments            30024 non-null  int64
 8   ip.ttl                  30024 non-null  int64
 9   ip.proto                30024 non-null  int64
 10  tcp.window_size         30024 non-null  int64
 11  tcp.ack                 30024 non-null  int64
 12  tcp.seq                 30024 non-null  int64
 13  tcp.len                 30024 non-null  int64
 14  tcp.stream              30024 non-null  int64
 15  tcp.urgent_pointer      30024 non-null  int64
 16  tcp.flags               30024 non-null  int64
 17  tcp.analysis.ack_rtt    30024 non-null  int64
 18  tcp.segments            30024 non-null  int64
 19  tcp.reassembled.length  30024 non-null  int64
 20  http.request            30024 non-null  int64
 21  udp.port                30024 non-null  int64
 22  frame.time_relative     30024 non-null  float64
 23  frame.time_delta        30024 non-null  float64
 24  tcp.time_relative       30024 non-null  float64
 25  tcp.time_delta          30024 non-null  float64
dtypes: float64(4), int64(20), object(2)
memory usage: 6.0+ MB

In [17]:
df_dos['ip.src'] = df_dos['ip.src'].str.replace('.', '', regex=False)
df_dos['ip.dst'] = df_dos['ip.dst'].str.replace('.', '', regex=False)
df_dos['ip.src'] = pd.to_numeric(df_dos['ip.src'], errors='coerce').astype('Int64')
df_dos['ip.dst'] = pd.to_numeric(df_dos['ip.dst'], errors='coerce').astype('Int64')

In [18]:
df_dos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30024 entries, 0 to 30023
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  30024 non-null  Int64
 1   ip.dst                  30024 non-null  Int64
 2   ip.len                  30024 non-null  int64
 3   ip.flags.df             30024 non-null  int64
 4   ip.flags.mf             30024 non-null  int64
 5   ip.fragment             30024 non-null  int64
 6   ip.fragment.count       30024 non-null  int64
 7   ip.fragments            30024 non-null  int64
 8   ip.ttl                  30024 non-null  int64
 9   ip.proto                30024 non-null  int64
 10  tcp.window_size         30024 non-null  int64
 11  tcp.ack                 30024 non-null  int64
 12  tcp.seq                 30024 non-null  int64
 13  tcp.len                 30024 non-null  int64
 14  tcp.stream              30024 non-null  int64
 15  tcp.urgent_pointer      30024 non-null  int64
 16  tcp.flags               30024 non-null  int64
 17  tcp.analysis.ack_rtt    30024 non-null  int64
 18  tcp.segments            30024 non-null  int64
 19  tcp.reassembled.length  30024 non-null  int64
 20  http.request            30024 non-null  int64
 21  udp.port                30024 non-null  int64
 22  frame.time_relative     30024 non-null  float64
 23  frame.time_delta        30024 non-null  float64
 24  tcp.time_relative       30024 non-null  float64
 25  tcp.time_delta          30024 non-null  float64
dtypes: Int64(2), float64(4), int64(20)
memory usage: 6.0 MB

In [19]:
df_dos['label']="ddos"

In [20]:
df_dos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30024 entries, 0 to 30023
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  30024 non-null  Int64
 1   ip.dst                  30024 non-null  Int64
 2   ip.len                  30024 non-null  int64
 3   ip.flags.df             30024 non-null  int64
 4   ip.flags.mf             30024 non-null  int64
 5   ip.fragment             30024 non-null  int64
 6   ip.fragment.count       30024 non-null  int64
 7   ip.fragments            30024 non-null  int64
 8   ip.ttl                  30024 non-null  int64
 9   ip.proto                30024 non-null  int64
 10  tcp.window_size         30024 non-null  int64
 11  tcp.ack                 30024 non-null  int64
 12  tcp.seq                 30024 non-null  int64
 13  tcp.len                 30024 non-null  int64
 14  tcp.stream              30024 non-null  int64
 15  tcp.urgent_pointer      30024 non-null  int64
 16  tcp.flags               30024 non-null  int64
 17  tcp.analysis.ack_rtt    30024 non-null  int64
 18  tcp.segments            30024 non-null  int64
 19  tcp.reassembled.length  30024 non-null  int64
 20  http.request            30024 non-null  int64
 21  udp.port                30024 non-null  int64
 22  frame.time_relative     30024 non-null  float64
 23  frame.time_delta        30024 non-null  float64
 24  tcp.time_relative       30024 non-null  float64
 25  tcp.time_delta          30024 non-null  float64
 26  label                   30024 non-null  object
dtypes: Int64(2), float64(4), int64(20), object(1)
memory usage: 6.2+ MB

In [21]:
full_df=pd.concat([half_df,df_dos], ignore_index=True)

In [22]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86657 entries, 0 to 86656
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  86657 non-null  Int64
 1   ip.dst                  86657 non-null  Int64
 2   ip.len                  86657 non-null  Int64
 3   ip.flags.df             86655 non-null  Int64
 4   ip.flags.mf             86657 non-null  Int64
 5   ip.fragment             86657 non-null  int64
 6   ip.fragment.count       86657 non-null  int64
 7   ip.fragments            86657 non-null  int64
 8   ip.ttl                  86657 non-null  Int64
 9   ip.proto                86657 non-null  Int64
 10  tcp.window_size         86657 non-null  float64
 11  tcp.ack                 86657 non-null  float64
 12  tcp.seq                 86657 non-null  float64
 13  tcp.len                 86657 non-null  float64
 14  tcp.stream              86657 non-null  float64
 15  tcp.urgent_pointer      86657 non-null  float64
 16  tcp.flags               86657 non-null  float64
 17  tcp.analysis.ack_rtt    86657 non-null  float64
 18  tcp.segments            86657 non-null  int64
 19  tcp.reassembled.length  86657 non-null  int64
 20  http.request            86657 non-null  int64
 21  udp.port                86657 non-null  int64
 22  frame.time_relative     86657 non-null  float64
 23  frame.time_delta        86657 non-null  float64
 24  tcp.time_relative       86657 non-null  float64
 25  tcp.time_delta          86657 non-null  float64
 26  label                   86657 non-null  object
dtypes: Int64(7), float64(12), int64(7), object(1)
memory usage: 18.4+ MB

In [23]:
full_df.shape

(86657, 27)

In [53]:
df_bngn=pd.read_csv("benign.csv")
df_bngn=df_bngn.dropna()
df_bngn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31030 entries, 0 to 31033
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  31030 non-null  object
 1   ip.dst                  31030 non-null  object
 2   ip.len                  31030 non-null  float64
 3   ip.flags.df             31030 non-null  object
 4   ip.flags.mf             31030 non-null  float64
 5   ip.fragment             31030 non-null  int64
 6   ip.fragment.count       31030 non-null  int64
 7   ip.fragments            31030 non-null  int64
 8   ip.ttl                  31030 non-null  float64
 9   ip.proto                31030 non-null  float64
 10  tcp.window_size         31030 non-null  float64
 11  tcp.ack                 31030 non-null  float64
 12  tcp.seq                 31030 non-null  float64
 13  tcp.len                 31030 non-null  float64
 14  tcp.stream              31030 non-null  float64
 15  tcp.urgent_pointer      31030 non-null  float64
 16  tcp.flags               31030 non-null  float64
 17  tcp.analysis.ack_rtt    31030 non-null  float64
 18  tcp.segments            31030 non-null  int64
 19  tcp.reassembled.length  31030 non-null  int64
 20  http.request            31030 non-null  int64
 21  udp.port                31030 non-null  object
 22  frame.time_relative     31030 non-null  float64
 23  frame.time_delta        31030 non-null  float64
 24  tcp.time_relative       31030 non-null  float64
 25  tcp.time_delta          31030 non-null  float64
dtypes: float64(16), int64(6), object(4)
memory usage: 6.4+ MB

In [54]:
df_bngn['ip.len'] = pd.to_numeric(df_bngn['ip.len'], errors='coerce').astype('Int64')
df_bngn['ip.flags.df'] = pd.to_numeric(df_bngn['ip.flags.df'], errors='coerce').astype('Int64')
df_bngn['ip.flags.mf'] = pd.to_numeric(df_bngn['ip.flags.mf'], errors='coerce').astype('Int64')
df_bngn['ip.ttl'] = pd.to_numeric(df_bngn['ip.ttl'], errors='coerce').astype('Int64')
df_bngn['ip.proto'] = pd.to_numeric(df_bngn['ip.proto'], errors='coerce').astype('Int64')
df_bngn['frame.time_delta'] = pd.to_numeric(df_bngn['frame.time_delta'], errors='coerce').astype('float64')
df_bngn['ip.src'] = df_bngn['ip.src'].str.replace('.', '', regex=False)
df_bngn['ip.dst'] = df_bngn['ip.dst'].str.replace('.', '', regex=False)
df_bngn['ip.src'] = pd.to_numeric(df_bngn['ip.src'], errors='coerce').astype('Int64')
df_bngn['ip.dst'] = pd.to_numeric(df_bngn['ip.dst'], errors='coerce').astype('Int64')
df_bngn['label']="benign"

In [55]:
df_bngn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31030 entries, 0 to 31033
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ip.src                  31030 non-null  Int64
 1   ip.dst                  31030 non-null  Int64
 2   ip.len                  31030 non-null  Int64
 3   ip.flags.df             31030 non-null  Int64
 4   ip.flags.mf             31030 non-null  Int64
 5   ip.fragment             31030 non-null  int64
 6   ip.fragment.count       31030 non-null  int64
 7   ip.fragments            31030 non-null  int64
 8   ip.ttl                  31030 non-null  Int64
 9   ip.proto                31030 non-null  Int64
 10  tcp.window_size         31030 non-null  float64
 11  tcp.ack                 31030 non-null  float64
 12  tcp.seq                 31030 non-null  float64
 13  tcp.len                 31030 non-null  float64
 14  tcp.stream              31030 non-null  float64
 15  tcp.urgent_pointer      31030 non-null  float64
 16  tcp.flags               31030 non-null  float64
 17  tcp.analysis.ack_rtt    31030 non-null  float64
 18  tcp.segments            31030 non-null  int64
 19  tcp.reassembled.length  31030 non-null  int64
 20  http.request            31030 non-null  int64
 21  udp.port                31030 non-null  object
 22  frame.time_relative     31030 non-null  float64
 23  frame.time_delta        31030 non-null  float64
 24  tcp.time_relative       31030 non-null  float64
 25  tcp.time_delta          31030 non-null  float64
 26  label                   31030 non-null  object
dtypes: Int64(7), float64(12), int64(6), object(2)
memory usage: 6.8+ MB

In [56]:
full_df=pd.concat([half_df,df_dos,df_bngn], ignore_index=True)
full_df["label"].nunique()

4

In [76]:

full_df.nunique()

ip.src                         8
ip.dst                         9
ip.len                        99
ip.flags.df                    2
ip.flags.mf                    1
ip.fragment                    1
ip.fragment.count              1
ip.fragments                   1
ip.ttl                        26
ip.proto                       3
tcp.window_size               31
tcp.ack                    10143
tcp.seq                      123
tcp.len                       98
tcp.stream                 19157
tcp.urgent_pointer             1
tcp.flags                      9
tcp.analysis.ack_rtt       37525
tcp.segments                   2
tcp.reassembled.length        12
http.request                   2
udp.port                       5
frame.time_relative       117685
frame.time_delta           63304
tcp.time_relative          76601
tcp.time_delta             67289
label                          4
dtype: int64

In [139]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder

# 1. Prepare data (using important features)
important_features = ['frame.time_relative', 'tcp.window_size', 'tcp.stream', 'ip.len', 'ip.ttl', 
                      'tcp.time_relative', 'tcp.flags', 'ip.flags.df', 'tcp.ack', 'tcp.analysis.ack_rtt']
le=LabelEncoder()
X = full_df.drop(columns=["label"])
y = le.fit_transform(full_df['label'])  # Convert labels to integers (e.g., 'ddos' -> 0)

# 2. Train-test split (80-20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Train Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 4. Evaluate the model
y_pred = model.predict(X_test)

# Print classification report and accuracy
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6038
           1       1.00      1.00      1.00      5346
           2       1.00      1.00      1.00      6035
           3       1.00      1.00      1.00      6119

    accuracy                           1.00     23538
   macro avg       1.00      1.00      1.00     23538
weighted avg       1.00      1.00      1.00     23538

Accuracy: 0.99974509304104

In [140]:
print(len(X))

117687

In [141]:
print(y)

[3 3 1 ... 0 0 0]

In [142]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117687 entries, 0 to 117686
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ip.src                  117687 non-null  Int64
 1   ip.dst                  117687 non-null  Int64
 2   ip.len                  117687 non-null  Int64
 3   ip.flags.df             117685 non-null  Int64
 4   ip.flags.mf             117687 non-null  Int64
 5   ip.fragment             117687 non-null  int64
 6   ip.fragment.count       117687 non-null  int64
 7   ip.fragments            117687 non-null  int64
 8   ip.ttl                  117687 non-null  Int64
 9   ip.proto                117687 non-null  Int64
 10  tcp.window_size         117687 non-null  float64
 11  tcp.ack                 117687 non-null  float64
 12  tcp.seq                 117687 non-null  float64
 13  tcp.len                 117687 non-null  float64
 14  tcp.stream              117687 non-null  float64
 15  tcp.urgent_pointer      117687 non-null  float64
 16  tcp.flags               117687 non-null  float64
 17  tcp.analysis.ack_rtt    117687 non-null  float64
 18  tcp.segments            117687 non-null  int64
 19  tcp.reassembled.length  117687 non-null  int64
 20  http.request            117687 non-null  int64
 21  udp.port                117687 non-null  object
 22  frame.time_relative     117687 non-null  float64
 23  frame.time_delta        117687 non-null  float64
 24  tcp.time_relative       117687 non-null  float64
 25  tcp.time_delta          117687 non-null  float64
 26  label                   117687 non-null  object
dtypes: Int64(7), float64(12), int64(6), object(2)
memory usage: 25.0+ MB

In [143]:
from sklearn.model_selection import cross_val_score
import numpy as np

cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')  # You can change scoring to 'f1_weighted', 'precision', etc.

# Print the cross-validation results
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean accuracy: {np.mean(cv_scores)}")
print(f"Standard deviation: {np.std(cv_scores)}")

Cross-validation scores: [0.81022177 0.99983006 0.99983005 0.9997026  0.94825169]
Mean accuracy: 0.9515672341264299
Standard deviation: 0.07343724778128041

In [144]:
import pandas as pd

new_data = pd.DataFrame({
    'ip.src': [192168202128],
    'ip.dst': [192168202129],
    'ip.len': [140],
    'ip.flags.df': [0],
    'ip.flags.mf': [0],
    'ip.fragment': [0],
    'ip.fragment.count': [0],
    'ip.fragments': [0],
    'ip.ttl': [64],
    'ip.proto': [6],
    'tcp.window_size': [512],
    'tcp.ack': [1177972782.0],
    'tcp.seq': [0],
    'tcp.len': [100],
    'tcp.stream': [3],
    'tcp.urgent_pointer': [0],
    'tcp.flags': [2],
    'tcp.analysis.ack_rtt': [0],
    'tcp.segments': [0],
    'tcp.reassembled.length': [0],
    'http.request': [0],
    'udp.port': [0],
    'frame.time_relative': [0.000000087],
    'frame.time_delta': [0.000000021],
    'tcp.time_relative': [0.0],
    'tcp.time_delta': [0.0]
})

In [145]:
y_pred_new = model.predict(new_data)
print(y_pred_new)

[2]

In [146]:
predicted_labels = le.inverse_transform(y_pred_new)
print("Predicted Label:", predicted_labels)

Predicted Label: ['ddos']

In [147]:
import joblib

# Save the trained model
joblib.dump(model, 'idsrandomforest.pkl')  # You can change the filename
joblib.dump(le, 'idslabel_encoder.pkl')

['idslabel_encoder.pkl']